<a href="https://colab.research.google.com/github/Mkmxyxnk69/apnacollege-demo/blob/main/AIMS_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('/content/placement.csv')

In [3]:
df

    iq  cgpa branch placement
0   80   7.8    cse        no
1   78   9.0     it       yes
2   90   7.0     se        no
3   45   NaN     it        no
4   77   7.7    cse        no
5   83   8.2    cse       yes
6   60   8.0    cse        no
7   88   NaN     se       yes
8   76   6.0     it        no
9   93   8.5     se       yes
10  75   NaN     it       yes
11  95   8.0     se       yes
12  90   9.0    cse       yes
13  67   8.0     it       yes
14  86   7.9     it       yes
15  70   NaN    cse        no
16  60   7.5     se       yes
17  89   6.5     se        no
18  92   9.0    cse       yes

In [4]:
#applying imputation(mean)
df['cgpa']=df['cgpa'].fillna(df['cgpa'].mean())

In [5]:
df

    iq      cgpa branch placement
0   80  7.800000    cse        no
1   78  9.000000     it       yes
2   90  7.000000     se        no
3   45  7.873333     it        no
4   77  7.700000    cse        no
5   83  8.200000    cse       yes
6   60  8.000000    cse        no
7   88  7.873333     se       yes
8   76  6.000000     it        no
9   93  8.500000     se       yes
10  75  7.873333     it       yes
11  95  8.000000     se       yes
12  90  9.000000    cse       yes
13  67  8.000000     it       yes
14  86  7.900000     it       yes
15  70  7.873333    cse        no
16  60  7.500000     se       yes
17  89  6.500000     se        no
18  92  9.000000    cse       yes

In [6]:
df['placement']=df['placement'].map({'yes':1,'no':0})

In [7]:
df

    iq      cgpa branch  placement
0   80  7.800000    cse          0
1   78  9.000000     it          1
2   90  7.000000     se          0
3   45  7.873333     it          0
4   77  7.700000    cse          0
5   83  8.200000    cse          1
6   60  8.000000    cse          0
7   88  7.873333     se          1
8   76  6.000000     it          0
9   93  8.500000     se          1
10  75  7.873333     it          1
11  95  8.000000     se          1
12  90  9.000000    cse          1
13  67  8.000000     it          1
14  86  7.900000     it          1
15  70  7.873333    cse          0
16  60  7.500000     se          1
17  89  6.500000     se          0
18  92  9.000000    cse          1

In [8]:
unique_branch=np.unique(df['branch'])
for i in unique_branch:
    df[i] = (df['branch'] == i).astype(int)

In [9]:
df

    iq      cgpa branch  placement  cse  it  se
0   80  7.800000    cse          0    1   0   0
1   78  9.000000     it          1    0   1   0
2   90  7.000000     se          0    0   0   1
3   45  7.873333     it          0    0   1   0
4   77  7.700000    cse          0    1   0   0
5   83  8.200000    cse          1    1   0   0
6   60  8.000000    cse          0    1   0   0
7   88  7.873333     se          1    0   0   1
8   76  6.000000     it          0    0   1   0
9   93  8.500000     se          1    0   0   1
10  75  7.873333     it          1    0   1   0
11  95  8.000000     se          1    0   0   1
12  90  9.000000    cse          1    1   0   0
13  67  8.000000     it          1    0   1   0
14  86  7.900000     it          1    0   1   0
15  70  7.873333    cse          0    1   0   0
16  60  7.500000     se          1    0   0   1
17  89  6.500000     se          0    0   0   1
18  92  9.000000    cse          1    1   0   0

In [10]:
df=df.drop('branch',axis=1)

In [11]:
df

    iq      cgpa  placement  cse  it  se
0   80  7.800000          0    1   0   0
1   78  9.000000          1    0   1   0
2   90  7.000000          0    0   0   1
3   45  7.873333          0    0   1   0
4   77  7.700000          0    1   0   0
5   83  8.200000          1    1   0   0
6   60  8.000000          0    1   0   0
7   88  7.873333          1    0   0   1
8   76  6.000000          0    0   1   0
9   93  8.500000          1    0   0   1
10  75  7.873333          1    0   1   0
11  95  8.000000          1    0   0   1
12  90  9.000000          1    1   0   0
13  67  8.000000          1    0   1   0
14  86  7.900000          1    0   1   0
15  70  7.873333          0    1   0   0
16  60  7.500000          1    0   0   1
17  89  6.500000          0    0   0   1
18  92  9.000000          1    1   0   0